[profile.default]
src = 'src'
out = 'out'
libs = ['lib']

# See more config options https://github.com/foundry-rs/foundry/tree/master/config

solc = "0.8.16"
optimizer = true
optimizer_runs = 100000

fuzz.runs = 1024

[profile.default.model_checker]
contracts = {'src/LibBytes.sol' = ['LibBytes'], 'src/LibMemCpy.sol' = ['LibMemCpy'], 'src/LibMemory.sol' = ['LibMemory'], 'src/LibPointer.sol' = ['LibPointer']}
engine = 'chc'
timeout = 10000
targets = ['assert', 'underflow', 'overflow', 'divByZero', 'constantCondition', 'popEmptyArray', 'outOfBounds']